# Generated by Django 3.1.2 on 2021-01-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=100)),
                ('currentLocation', models.CharField(default='', max_length=200)),
                ('closestBusStop', models.CharField(default='', max_length=200)),
                ('route', models.CharField(default='', max_length=200)),
                ('ETA', models.CharField(default='', max_length=100)),
                ('ride_date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=200)),
                ('user_id', models.CharField(default='', max_length=100)),
                ('passwd', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
