# Generated by Django 3.1.6 on 2021-02-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210218_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ride2',
            new_name='game',
        ),
    ]
