# Generated by Django 3.1.6 on 2021-02-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210218_1805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ride',
            new_name='Favorite_Ride',
        ),
        migrations.RenameModel(
            old_name='game',
            new_name='Ride2',
        ),
    ]
