# Generated by Django 3.1.6 on 2021-02-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210218_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite_ride',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
