# Generated by Django 3.1.6 on 2021-02-28 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_favorite_ride_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ride2',
        ),
    ]
